-- changelog tab -- 
local Tabs = require 'comfy_panel.main'

local function add_changelog(player, element)
	local changelog_scrollpanel = element.add { type = "scroll-pane", name = "scroll_pane", direction = "vertical", horizontal_scroll_policy = "never", vertical_scroll_policy = "auto"}
	changelog_scrollpanel.style.maximal_height = 530
	
	local changelog_change = {}
	table.insert(changelog_change,"2021-12-17")
	table.insert(changelog_change,"Auto tagging outpost")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Clear clipboard on game join")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Add more threat to compensate revive")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Set path_finder settings")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Increased copper and stone size by 10%")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Fix silo grief (mirroring)")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Add changelog tab")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Update/prevent landfilling by untrusted user")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Do not allow ghosts on enemy side")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Limited threshold of biters reviving to 90% chance")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Removed trust check on clear-corpses command")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Added infinite spy when white science is thrown")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Fix difficulty GUI lag spikes")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-06")
	table.insert(changelog_change,"Improve biter performance")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"fix antigrief inconsistency")
	table.insert(changelog_change,"XVhc6A")
	table.insert(changelog_change,"2021-11-19")
	table.insert(changelog_change,"Quick and dirty way to fix desync")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-12-06")
	table.insert(changelog_change,"Added special_games system")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-11-08")
	table.insert(changelog_change,"Change text warning to accurately reflect mechanics")
	table.insert(changelog_change,"Tomab")
	table.insert(changelog_change,"2021-11-10")
	table.insert(changelog_change,"Improved readme")
	table.insert(changelog_change,"Tomab")
	table.insert(changelog_change,"2021-11-21")
	table.insert(changelog_change,"Ban improvements")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-10-30")
	table.insert(changelog_change,"mutes - make mute great again")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-10-30")
	table.insert(changelog_change,"shout-fix: fix shout logging so that non admin shouts get logged too")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-11-25")
	table.insert(changelog_change,"Remove vehicle from silo")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-11-21")
	table.insert(changelog_change,"First join gui minor tweaks")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-10-11")
	table.insert(changelog_change,"Add join_random_button")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-10-11")
	table.insert(changelog_change,"Top gui visual cleanup")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-09-19")
	table.insert(changelog_change,"spying-fix: if you've chosen a team, remove space sci button")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-09-19")
	table.insert(changelog_change,"Print msg to admin upon offshore pump mining")
	table.insert(changelog_change,"gabrielchl")
	table.insert(changelog_change,"2021-08-31")
