name: Run tests

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: docker/build-push-action@v3
      with:
        file: tests/Dockerfile
        tags: fbb:latest

    - uses: addnab/docker-run-action@v3
      with:
        image: fbb:latest
        run: /scenario.sh Factorio-Biter-Battles
